
// get all music constants
export const GET_ALL_MUSIC = 'GET_ALL_MUSIC'
export const GET_ALL_MUSIC_SUCCESS = 'GET_ALL_MUSIC_SUCCESS'
export const GET_ALL_MUSIC_FAILED = 'GET_ALL_MUSIC_FAILED'

// get all favorite music by user constants
export const GET_ALL_FAVORITE_MUSIC = 'GET_ALL_FAVORITE_MUSIC'
export const GET_ALL_FAVORITE_MUSIC_SUCCESS =  'GET_ALL_FAVORITE_MUSIC_SUCCESS'
export const GET_ALL_FAVORITE_MUSIC_FAILED = 'GET_ALL_FAVORITE_MUSIC_FAILED'